# **Importing Libraries**

In [1]:
import pandas as pd
import plotly.express as px

# **Exploring Data**

In [2]:
data = pd.read_csv('ai_job_dataset.csv')

In [3]:
data.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  str
 1   job_title               15000 non-null  str
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  str
 4   experience_level        15000 non-null  str
 5   employment_type         15000 non-null  str
 6   company_location        15000 non-null  str
 7   company_size            15000 non-null  str
 8   employee_residence      15000 non-null  str
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  str
 11  education_required      15000 non-null  str
 12  years_experience        15000 non-null  int64
 13  industry                15000 non-null  str
 14  posting_date            15000 non-null  str
 15  application_deadline    15000 non-null  str
 16  job_description_length  15000 non-null  int64
 17  benefits_score          15000 non-null  float64
 18  company_name            15000 non-null  str
dtypes: float64(1), int64(4), str(14)
memory usage: 4.1 MB

In [5]:
data.describe()

,salary_usd,remote_ratio,years_experience,job_description_length,benefits_score
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,115348.965133,49.483333,6.253200,1503.314733,7.504273
std,60260.940438,40.812712,5.545768,576.127083,1.450870
min,32519.000000,0.000000,0.000000,500.000000,5.000000
25%,70179.750000,0.000000,2.000000,1003.750000,6.200000
50%,99705.000000,50.000000,5.000000,1512.000000,7.500000
75%,146408.500000,100.000000,10.000000,2000.000000,8.800000
max,399095.000000,100.000000,19.000000,2499.000000,10.000000

In [6]:
data.isna().sum()

job_id                    0
job_title                 0
salary_usd                0
salary_currency           0
experience_level          0
employment_type           0
company_location          0
company_size              0
employee_residence        0
remote_ratio              0
required_skills           0
education_required        0
years_experience          0
industry                  0
posting_date              0
application_deadline      0
job_description_length    0
benefits_score            0
company_name              0
dtype: int64

In [7]:
data.duplicated().sum()

np.int64(0)

# **Cleaning**

In [8]:
df = data.copy()
df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [9]:
# drop unnecessary columns
df.drop(['job_id', 'salary_currency', 'employee_residence', 'job_description_length', 'benefits_score'], axis=1, inplace=True)

In [10]:
df.head()

,job_title,salary_usd,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,company_name
0,AI Research Scientist,90376,SE,CT,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,Smart Analytics
1,AI Software Engineer,61895,EN,CT,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,TechCorp Inc
2,AI Specialist,152626,MI,FL,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,Autonomous Tech
3,NLP Engineer,80215,SE,FL,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,Future Systems
4,AI Consultant,54624,EN,PT,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,Advanced Robotics

In [11]:
# rename columns 
df.rename(columns={'salary_usd':'annual_salary'}, inplace=True)

In [12]:
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,company_name
0,AI Research Scientist,90376,SE,CT,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,Smart Analytics
1,AI Software Engineer,61895,EN,CT,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,TechCorp Inc
2,AI Specialist,152626,MI,FL,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,Autonomous Tech
3,NLP Engineer,80215,SE,FL,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,Future Systems
4,AI Consultant,54624,EN,PT,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,Advanced Robotics

## Feature Engineering

In [13]:
df['monthly_salary'] = df['annual_salary'] / 12
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,company_name,monthly_salary
0,AI Research Scientist,90376,SE,CT,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,Smart Analytics,7531.333333
1,AI Software Engineer,61895,EN,CT,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,TechCorp Inc,5157.916667
2,AI Specialist,152626,MI,FL,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,Autonomous Tech,12718.833333
3,NLP Engineer,80215,SE,FL,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,Future Systems,6684.583333
4,AI Consultant,54624,EN,PT,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,Advanced Robotics,4552.000000

In [14]:
df.experience_level = df.experience_level.apply(lambda x: 'Entry' if x == 'EN' else 'Mid' if x == 'MI' else 'Senior' if x == 'SE' else 'Executive')
df.experience_level

0           Senior
1            Entry
2              Mid
3           Senior
4            Entry
           ...
14995        Entry
14996        Entry
14997    Executive
14998        Entry
14999          Mid
Name: experience_level, Length: 15000, dtype: str

In [15]:
df.employment_type = df.employment_type.apply(lambda x: 'Full Time' if x == 'FT' else 'Part Time' if x == 'PT' else 'Contract' if x == 'CT' else 'Freelance')
df.employment_type

0         Contract
1         Contract
2        Freelance
3        Freelance
4        Part Time
           ...
14995    Freelance
14996     Contract
14997     Contract
14998    Full Time
14999    Part Time
Name: employment_type, Length: 15000, dtype: str

In [16]:
df.company_size = df.company_size.apply(lambda x: 'Small <50' if x == 'S' else 'Medium 50-250' if x == 'M' else 'Large >250')
df.company_size

0        Medium 50-250
1        Medium 50-250
2           Large >250
3        Medium 50-250
4            Small <50
             ...
14995        Small <50
14996    Medium 50-250
14997       Large >250
14998    Medium 50-250
14999        Small <50
Name: company_size, Length: 15000, dtype: str

In [17]:
df['remote_state'] = df['remote_ratio'].apply(lambda x: 'No remote' if x == 0 else 'Hybrid' if x == 50 else 'Fully remote')
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,company_name,monthly_salary,remote_state
0,AI Research Scientist,90376,Senior,Contract,China,Medium 50-250,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,Smart Analytics,7531.333333,Hybrid
1,AI Software Engineer,61895,Entry,Contract,Canada,Medium 50-250,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,TechCorp Inc,5157.916667,Fully remote
2,AI Specialist,152626,Mid,Freelance,Switzerland,Large >250,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,Autonomous Tech,12718.833333,No remote
3,NLP Engineer,80215,Senior,Freelance,India,Medium 50-250,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,Future Systems,6684.583333,Hybrid
4,AI Consultant,54624,Entry,Part Time,France,Small <50,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,Advanced Robotics,4552.000000,Fully remote

In [18]:
# extract each skill from the required_skills column
skill_set = set()
for item in df.required_skills.apply(lambda x: x.split(', ')):
    for skill in item:
        skill_set.add(skill)

In [19]:
skill_set

{'AWS',
 'Azure',
 'Computer Vision',
 'Data Visualization',
 'Deep Learning',
 'Docker',
 'GCP',
 'Git',
 'Hadoop',
 'Java',
 'Kubernetes',
 'Linux',
 'MLOps',
 'Mathematics',
 'NLP',
 'PyTorch',
 'Python',
 'R',
 'SQL',
 'Scala',
 'Spark',
 'Statistics',
 'Tableau',
 'TensorFlow'}

In [20]:
# create a new column for each skill
for skill in skill_set:
    df[skill] = df.required_skills.apply(lambda x: 1 if skill in x else 0)

In [21]:
# extracting weekend & weekday
df.posting_date = df.posting_date.astype('datetime64[ms]')

In [22]:
df['is_weekend'] = df.posting_date.dt.day_name().apply(lambda x: 'Weekend' if x in ['Friday', 'Saturday'] else 'Weekday')

In [23]:
# month column
df['posting_month'] = df.posting_date.dt.month
df.posting_month

0        10
1        11
2         3
3        12
4         4
         ..
14995     2
14996    10
14997     3
14998     3
14999     7
Name: posting_month, Length: 15000, dtype: int32

In [24]:
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
0,AI Research Scientist,90376,Senior,Contract,China,Medium 50-250,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,...,0,0,0,0,0,0,0,0,Weekend,10
1,AI Software Engineer,61895,Entry,Contract,Canada,Medium 50-250,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,...,0,1,0,0,0,1,0,1,Weekday,11
2,AI Specialist,152626,Mid,Freelance,Switzerland,Large >250,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,...,0,0,0,0,0,0,0,0,Weekday,3
3,NLP Engineer,80215,Senior,Freelance,India,Medium 50-250,50,"Scala, SQL, Linux, Python",PhD,7,...,0,0,0,1,0,1,0,0,Weekday,12
4,AI Consultant,54624,Entry,Part Time,France,Small <50,100,"MLOps, Java, Tableau, Python",Master,0,...,1,0,0,0,0,1,0,0,Weekday,4

In [25]:
# drop unnecessary columns
df.drop(['remote_ratio', 'required_skills'], axis=1, inplace=True)

## Saving Clean Data

In [26]:
df.to_csv("ai_job_cleaned.csv", index=False)

# **EDA**

In [27]:
df = pd.read_csv("ai_job_cleaned.csv")

In [28]:
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
0,AI Research Scientist,90376,Senior,Contract,China,Medium 50-250,Bachelor,9,Automotive,2024-10-18,...,0,0,0,0,0,0,0,0,Weekend,10
1,AI Software Engineer,61895,Entry,Contract,Canada,Medium 50-250,Master,1,Media,2024-11-20,...,0,1,0,0,0,1,0,1,Weekday,11
2,AI Specialist,152626,Mid,Freelance,Switzerland,Large >250,Associate,2,Education,2025-03-18,...,0,0,0,0,0,0,0,0,Weekday,3
3,NLP Engineer,80215,Senior,Freelance,India,Medium 50-250,PhD,7,Consulting,2024-12-23,...,0,0,0,1,0,1,0,0,Weekday,12
4,AI Consultant,54624,Entry,Part Time,France,Small <50,Master,0,Media,2025-04-15,...,1,0,0,0,0,1,0,0,Weekday,4

In [29]:
# 1. What is the average monthly salary?
df['monthly_salary'].mean()

np.float64(9612.413761111113)

In [30]:
# 2. Who has the highest monthly salary?
max_salary = df.monthly_salary.max()
max_salary

np.float64(33257.916666666664)

In [31]:
df[df.monthly_salary == df.monthly_salary.max()]

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
9891,Machine Learning Researcher,399095,Executive,Part Time,Switzerland,Large >250,Master,10,Retail,2024-07-10,...,0,0,0,0,0,1,0,0,Weekday,7

In [32]:
df.monthly_salary.idxmax()

9891

In [33]:
df.iloc[[df.monthly_salary.idxmax()]]

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
9891,Machine Learning Researcher,399095,Executive,Part Time,Switzerland,Large >250,Master,10,Retail,2024-07-10,...,0,0,0,0,0,1,0,0,Weekday,7

In [34]:
#3. Who has the highest monthly salary and work Full-Time job?
df.iloc[[df[df.employment_type == 'Full Time'].monthly_salary.idxmax()]]

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
12803,AI Specialist,390292,Executive,Full Time,Switzerland,Large >250,Associate,11,Real Estate,2024-12-27,...,0,0,1,0,0,0,0,0,Weekend,12

In [35]:
# 3. Who has the lowest monthly salary?
df[df.monthly_salary == df.monthly_salary.min()]

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
9549,Computer Vision Engineer,32519,Entry,Full Time,India,Small <50,Master,0,Energy,2025-03-27,...,0,0,0,1,1,1,0,0,Weekday,3

In [36]:
df.iloc[[df.monthly_salary.idxmin()]]

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
9549,Computer Vision Engineer,32519,Entry,Full Time,India,Small <50,Master,0,Energy,2025-03-27,...,0,0,0,1,1,1,0,0,Weekday,3

In [37]:
# 1. What is the average monthly salary?
df.monthly_salary.mean()

np.float64(9612.413761111113)

In [38]:
# 2. Who has the highest monthly salary?
df[df.monthly_salary == df.monthly_salary.max()]

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
9891,Machine Learning Researcher,399095,Executive,Part Time,Switzerland,Large >250,Master,10,Retail,2024-07-10,...,0,0,0,0,0,1,0,0,Weekday,7

In [39]:
# 4. Who has the lowest monthly salary?
df[df.monthly_salary == df.monthly_salary.min()]

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
9549,Computer Vision Engineer,32519,Entry,Full Time,India,Small <50,Master,0,Energy,2025-03-27,...,0,0,0,1,1,1,0,0,Weekday,3

In [40]:
# 5. What is the most common job title?
df.job_title.value_counts().head(1).reset_index()

                     job_title  count
0  Machine Learning Researcher    808

In [41]:
# 6. Does company size affect the average monthly salary?
df.groupby('company_size')['monthly_salary'].mean().reset_index()

# Yes, when company size increases, the monthly salary increases

    company_size  monthly_salary
0     Large >250    10860.204315
1  Medium 50-250     9466.686420
2      Small <50     8512.244175

In [42]:
# 7. Which job title has the highest average monthly salary?
df.groupby('job_title')['monthly_salary'].mean().reset_index().sort_values(by='monthly_salary', ascending=False).head(1)

       job_title  monthly_salary
5  AI Specialist    10047.563187

In [43]:
# 9. Which company location has the highest average salary in each industry?
result = df.groupby(['industry', 'company_location'])['monthly_salary'].mean().reset_index()
result

           industry company_location  monthly_salary
0        Automotive        Australia    10069.046970
1        Automotive          Austria     7068.183962
2        Automotive           Canada     8252.121212
3        Automotive            China     6914.541667
4        Automotive          Denmark    14253.233607
..              ...              ...             ...
295  Transportation      South Korea     7174.372024
296  Transportation           Sweden    10044.844444
297  Transportation      Switzerland    14891.785256
298  Transportation   United Kingdom    11042.782986
299  Transportation    United States    11362.129944

[300 rows x 3 columns]

In [44]:
result.iloc[result.groupby('industry')['monthly_salary'].idxmax()]

               industry company_location  monthly_salary
17           Automotive      Switzerland    14270.289308
33           Consulting           Norway    14908.579787
57            Education      Switzerland    13958.254630
77               Energy      Switzerland    15799.792593
99              Finance    United States    14162.698718
117              Gaming      Switzerland    14130.527174
137          Government      Switzerland    13544.045635
144          Healthcare          Denmark    14160.067073
177       Manufacturing      Switzerland    14192.107372
184               Media          Denmark    15365.567308
213         Real Estate           Norway    14539.775758
224              Retail          Denmark    14803.456061
257          Technology      Switzerland    17206.412698
264  Telecommunications          Denmark    14769.258503
297      Transportation      Switzerland    14891.785256

In [45]:
# is applications more in weekend?
df.is_weekend.value_counts(normalize=True)*100

is_weekend
Weekday    71.026667
Weekend    28.973333
Name: proportion, dtype: float64

## **loc & iloc**
- loc: Search by Real Index
- iloc: Search by Index

In [46]:
data = pd.DataFrame(index=['a', 'b', 'c'], columns='col1 col2 col3'.split(),
                    data=[[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

data

   col1  col2  col3
a     1     2     3
b     4     5     6
c     7     8     9

In [47]:
# iloc ==> Search by index (even it doesn't exist)
# loc ==> Search by Real Index
data.loc[['a']]

   col1  col2  col3
a     1     2     3

In [48]:
data.iloc[[0]]

   col1  col2  col3
a     1     2     3

# **Visualization**

In [49]:
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,MLOps,Mathematics,Statistics,Scala,Computer Vision,Python,R,AWS,is_weekend,posting_month
0,AI Research Scientist,90376,Senior,Contract,China,Medium 50-250,Bachelor,9,Automotive,2024-10-18,...,0,0,0,0,0,0,0,0,Weekend,10
1,AI Software Engineer,61895,Entry,Contract,Canada,Medium 50-250,Master,1,Media,2024-11-20,...,0,1,0,0,0,1,0,1,Weekday,11
2,AI Specialist,152626,Mid,Freelance,Switzerland,Large >250,Associate,2,Education,2025-03-18,...,0,0,0,0,0,0,0,0,Weekday,3
3,NLP Engineer,80215,Senior,Freelance,India,Medium 50-250,PhD,7,Consulting,2024-12-23,...,0,0,0,1,0,1,0,0,Weekday,12
4,AI Consultant,54624,Entry,Part Time,France,Small <50,Master,0,Media,2025-04-15,...,1,0,0,0,0,1,0,0,Weekday,4

In [50]:
px.histogram(df, x='monthly_salary', nbins=10, title='Annual Salary distribution',
             labels={'count': 'Frequency', 'annual_salary':'Annual Salary'}, template='plotly_dark',
             text_auto=True)

In [51]:
# experience level
exp_lvl_df = df.experience_level.value_counts().reset_index()
exp_lvl_df

  experience_level  count
0              Mid   3781
1        Executive   3760
2           Senior   3741
3            Entry   3718

In [52]:
df.groupby(['industry', 'experience_level'])['monthly_salary'].count().reset_index()

              industry experience_level  monthly_salary
0           Automotive            Entry             275
1           Automotive        Executive             243
2           Automotive              Mid             249
3           Automotive           Senior             253
4           Consulting            Entry             245
5           Consulting        Executive             274
6           Consulting              Mid             246
7           Consulting           Senior             255
8            Education            Entry             228
9            Education        Executive             241
10           Education              Mid             257
11           Education           Senior             230
12              Energy            Entry             229
13              Energy        Executive             265
14              Energy              Mid             258
15              Energy           Senior             224
16             Finance            Entry             245
17             Finance        Executive             247
18             Finance              Mid             249
19             Finance           Senior             243
20              Gaming            Entry             267
21              Gaming        Executive             234
22              Gaming              Mid             245
23              Gaming           Senior             221
24          Government            Entry             227
25          Government        Executive             248
26          Government              Mid             271
27          Government           Senior             252
28          Healthcare            Entry             252
29          Healthcare        Executive             257
30          Healthcare              Mid             250
31          Healthcare           Senior             238
32       Manufacturing            Entry             242
33       Manufacturing        Executive             236
34       Manufacturing              Mid             211
35       Manufacturing           Senior             273
36               Media            Entry             252
37               Media        Executive             279
38               Media              Mid             261
39               Media           Senior             253
40         Real Estate            Entry             255
41         Real Estate        Executive             239
42         Real Estate              Mid             267
43         Real Estate           Senior             246
44              Retail            Entry             276
45              Retail        Executive             248
46              Retail              Mid             276
47              Retail           Senior             263
48          Technology            Entry             252
49          Technology        Executive             247
50          Technology              Mid             230
51          Technology           Senior             282
52  Telecommunications            Entry             241
53  Telecommunications        Executive             250
54  Telecommunications              Mid             250
55  Telecommunications           Senior             256
56      Transportation            Entry             232
57      Transportation        Executive             252
58      Transportation              Mid             261
59      Transportation           Senior             252

In [53]:
px.bar(df.groupby(['industry', 'experience_level'])['monthly_salary'].count().reset_index(),
       x='industry', y='monthly_salary', color='experience_level', barmode='stack')

In [54]:
px.bar(df.groupby(['industry', 'experience_level'])['annual_salary'].count().reset_index(),
       x='industry', y='annual_salary', color='experience_level', barmode='group')

In [55]:
px.bar(exp_lvl_df, x='experience_level', y='count',
       labels={'count':'Number of Jobs', 'experience_level':'Experience Level'}, 
       title='Number of Jobs by Exp. Level',color_continuous_scale='Reds', color='count', template='plotly_dark')

In [56]:
df.groupby('experience_level')['annual_salary'].mean().reset_index()

  experience_level  annual_salary
0            Entry   63133.377084
1        Executive  187723.647340
2              Mid   87955.471833
3           Senior  122187.657845

In [64]:
px.pie(df.experience_level.value_counts().reset_index(), hole=0.5,
       names='experience_level', values='count', title='Experience Level Propotions', template='plotly_dark')

In [400]:
px.histogram(df,x="annual_salary",title="Annual Salary",template="simple_white",labels={"annual_salary":"Annual Salary"})

In [401]:
px.pie(df.experience_level.value_counts().reset_index(),names="experience_level",values ="count",title = "Experience Level",template="plotly_dark")

In [402]:
df.groupby("experience_level")["annual_salary"].mean().reset_index()

  experience_level  annual_salary
0            Entry   63133.377084
1        Executive  187723.647340
2              Mid   87955.471833
3           Senior  122187.657845

In [403]:
df.posting_month.value_counts().reset_index().sort_values(by='posting_month')

    posting_month  count
1               1   1917
3               2   1767
2               3   1854
0               4   1927
7               5    955
9               6    938
5               7    959
6               8    958
11              9    895
8              10    949
10             11    922
4              12    959

In [404]:
px.line(df.posting_month.value_counts().reset_index().sort_values(by='posting_month'), x='posting_month', y='count',
        markers=True, template='plotly_dark')

In [405]:
df.head()

,job_title,annual_salary,experience_level,employment_type,company_location,company_size,education_required,years_experience,industry,posting_date,...,GCP,Data Visualization,Statistics,AWS,Tableau,NLP,Linux,TensorFlow,is_weekend,posting_month
0,AI Research Scientist,90376,Senior,Contract,China,Medium 50-250,Bachelor,9,Automotive,2024-10-18,...,0,0,0,0,1,1,1,0,Weekend,10
1,AI Software Engineer,61895,Entry,Contract,Canada,Medium 50-250,Master,1,Media,2024-11-20,...,0,0,0,1,0,0,0,0,Weekday,11
2,AI Specialist,152626,Mid,Freelance,Switzerland,Large >250,Associate,2,Education,2025-03-18,...,0,0,0,0,0,1,0,0,Weekday,3
3,NLP Engineer,80215,Senior,Freelance,India,Medium 50-250,PhD,7,Consulting,2024-12-23,...,0,0,0,0,0,0,1,0,Weekday,12
4,AI Consultant,54624,Entry,Part Time,France,Small <50,Master,0,Media,2025-04-15,...,0,0,0,0,1,0,0,0,Weekday,4

In [406]:
px.scatter(df, y='annual_salary', x='years_experience', color='experience_level')

In [407]:
px.scatter(df, y='annual_salary', x='years_experience', symbol='experience_level', color='experience_level',
           color_discrete_sequence=['black', 'yellow', 'green', 'red'])